plugins {
    id 'com.sunny.framework.common' apply false
    id 'org.springframework.boot' apply false
    id 'maven-publish'
}

group = 'com.sunny'
version = sunnyFrameworkVersion

def specialModules = [
        "sunny-framework-bom",
        "sunny-framework-test",
        "sunny-generator-mybatis"
]

tasks.register("clean") {
    group = "build"
    dependsOn gradle.includedBuilds*.task(":clean")
}

tasks.matching { it.name.startsWith('publish') }.each {
    tasks.named("${it.name}") {
        dependsOn gradle.includedBuilds*.task(":${it.name}")
    }
}

subprojects {
    apply plugin: 'io.spring.dependency-management'

    group = rootProject.group
    version = sunnyFrameworkVersion

    dependencyManagement {
        generatedPomCustomization {
            enabled = false
        }
        imports {
            mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
        }
    }

    apply from: "${project.rootDir}/dependency.gradle"

    if (!specialModules.contains(name)) {
        apply plugin: 'java-library'
        apply plugin: 'com.sunny.framework.common'
        apply plugin: 'com.sunny.framework.spring'

        apply plugin: 'com.sunny.framework.publish'
    }
}