plugins {
    id 'java-library'
    id 'com.sunny.framework.common'
    id 'com.sunny.framework.lombok'
    id 'com.sunny.framework.spring'

    id 'org.springframework.boot'
}

dependencies {

    implementation(project(":sunny-framework-web")) {
        exclude group: "com.alibaba.cloud", module: "spring-cloud-starter-alibaba-nacos-config"
        exclude group: "com.alibaba.cloud", module: "spring-cloud-starter-alibaba-nacos-discovery"
    }

    testImplementation(project(":sunny-framework-bundle")) {
        exclude group: "com.alibaba.cloud", module: "spring-cloud-starter-alibaba-nacos-config"
        exclude group: "com.alibaba.cloud", module: "spring-cloud-starter-alibaba-nacos-discovery"
    }

}