name: Build

on:
  push:
    branches: 
      - main
      - boot-*

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - run: |
          [ -f "$HOME/.bashrc" ] && source $HOME/.bashrc
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew publishToMavenLocal publishAllPublicationsToHomeSnapshotsRepository